# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'StartWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from GLOBALS import  *
from PyQt5 import QtCore, QtGui, QtWidgets
from rc import startWindowBG_rc


import CreateLoginWindow, StoreWindow
import sys
# import backupFile



class Ui_StartWindow(object):


    def setupUi(self, StartWindow):


        ''' FUNCTIONS '''
        # Window Routing Functions
        def enterCreateLoginWindow():
            # Showing Create Window
            self.window = QtWidgets.QMainWindow()
            self.ui = CreateLoginWindow.Ui_CreateLoginWindow()
            self.ui.setupUi(self.window)
            self.window.show()

            # Hiding the Start Window
            StartWindow.hide()

            print("Routing to Create Login Window")

        # What do you think this does??
        def exitApp():
            sys.exit()

        StartWindow.setWindowFlags(QtCore.Qt.FramelessWindowHint) # Hides the title bar
        StartWindow.setObjectName("StartWindow")
        StartWindow.resize(1000, 625)
        StartWindow.setMinimumSize(QtCore.QSize(1000, 625))
        StartWindow.setMaximumSize(QtCore.QSize(1200, 625))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Web Development Related/Website Materials/Medias/Website CDNS/animex/icons/tab-icons/favicon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        StartWindow.setWindowIcon(icon)
        StartWindow.setLayoutDirection(QtCore.Qt.RightToLeft)
        StartWindow.setAutoFillBackground(False)
        StartWindow.setStyleSheet("background-image: url(:/newPrefix/imgs/startWindowBG.png);")
        self.centralwidget = QtWidgets.QWidget(StartWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setAutoFillBackground(False)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.startWindow_MainHeadingLabel = QtWidgets.QLabel(self.frame)
        self.startWindow_MainHeadingLabel.setGeometry(QtCore.QRect(0, 130, 981, 161))
        font = QtGui.QFont()
        font.setFamily("ARS Maquette Pro Black")
        font.setPointSize(72)
        font.setBold(True)
        font.setWeight(75)
        self.startWindow_MainHeadingLabel.setFont(font)
        self.startWindow_MainHeadingLabel.setStyleSheet("QLabel {\n"
"    color: white;\n"
"}")
        self.startWindow_MainHeadingLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.startWindow_MainHeadingLabel.setObjectName("startWindow_MainHeadingLabel")
        self.startWindow_MainTextLabel = QtWidgets.QLabel(self.frame)
        self.startWindow_MainTextLabel.setGeometry(QtCore.QRect(-4, 250, 991, 81))
        font = QtGui.QFont()
        font.setFamily("Public Sans Medium")
        font.setPointSize(20)
        self.startWindow_MainTextLabel.setFont(font)
        self.startWindow_MainTextLabel.setStyleSheet("QLabel {\n"
"    color: white;\n"
"}")
        self.startWindow_MainTextLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.startWindow_MainTextLabel.setObjectName("startWindow_MainTextLabel")
        self.startWindow_ExitBtn = QtWidgets.QPushButton(self.frame)
        self.startWindow_ExitBtn.setGeometry(QtCore.QRect(500, 360, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Public Sans Medium")
        font.setPointSize(11)
        self.startWindow_ExitBtn.setFont(font)
        self.startWindow_ExitBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.startWindow_ExitBtn.clicked.connect(exitApp)
        self.startWindow_ExitBtn.setAutoFillBackground(False)
        self.startWindow_ExitBtn.setStyleSheet("background: rgb(20, 134, 255);\n"
"color: white;\n"
"border: none;")
        self.startWindow_ExitBtn.setObjectName("startWindow_ExitBtn")
        self.startWindow_CreateLoginBtn = QtWidgets.QPushButton(self.frame)
        self.startWindow_CreateLoginBtn.clicked.connect(enterCreateLoginWindow)
        self.startWindow_CreateLoginBtn.setGeometry(QtCore.QRect(350, 360, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Public Sans Medium")
        font.setPointSize(11)
        self.startWindow_CreateLoginBtn.setFont(font)
        self.startWindow_CreateLoginBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.startWindow_CreateLoginBtn.setAutoFillBackground(False)
        self.startWindow_CreateLoginBtn.setStyleSheet("background: rgb(20, 134, 255);\n"
"color: white;\n"
"border: none;")
        self.startWindow_CreateLoginBtn.setObjectName("startWindow_CreateLoginBtn")
        self.startWindow_TechUsedLabel = QtWidgets.QLabel(self.frame)
        self.startWindow_TechUsedLabel.setGeometry(QtCore.QRect(-4, 530, 991, 20))
        font = QtGui.QFont()
        font.setFamily("Public Sans Medium")
        font.setPointSize(9)
        self.startWindow_TechUsedLabel.setFont(font)
        self.startWindow_TechUsedLabel.setStyleSheet("color: white;")
        self.startWindow_TechUsedLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.startWindow_TechUsedLabel.setObjectName("startWindow_TechUsedLabel")
        self.verticalLayout.addWidget(self.frame)
        StartWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(StartWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 21))
        self.menubar.setObjectName("menubar")
        StartWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(StartWindow)
        self.statusbar.setObjectName("statusbar")
        StartWindow.setStatusBar(self.statusbar)

        self.retranslateUi(StartWindow)
        QtCore.QMetaObject.connectSlotsByName(StartWindow)

    def retranslateUi(self, StartWindow):
        _translate = QtCore.QCoreApplication.translate
        StartWindow.setWindowTitle(_translate("StartWindow", "ANIMEX - Welcome"))
        self.startWindow_MainHeadingLabel.setText(_translate("StartWindow", "ANIMEX"))
        self.startWindow_MainTextLabel.setText(_translate("StartWindow", "Anime/Manga Store Program"))
        self.startWindow_ExitBtn.setText(_translate("StartWindow", "EXIT PROGRAM"))
        self.startWindow_CreateLoginBtn.setText(_translate("StartWindow", "CREATE/LOGIN"))
        self.startWindow_TechUsedLabel.setText(_translate("StartWindow", "Created w/ QtDesigner and Python"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    StartWindow = QtWidgets.QMainWindow()
    ui = Ui_StartWindow()
    ui.setupUi(StartWindow)
    StartWindow.show()

    # Backing up files (UNCOMMENT THIS IF U WANT TO BACKUP YOUR FILES)
    # backupFile.backupAllFiles()

    sys.exit(app.exec_())
